version: "3.7"

services:
  app:
    image: kishikawakatsumi/swift-ast-explorer:latest
    container_name: swift-ast-explorer
    depends_on:
      - letsencrypt
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      VIRTUAL_HOST: swift-ast-explorer.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: swift-ast-explorer.com
      LETSENCRYPT_EMAIL: kishikawakatsumi@mac.com
    ports:
      - 8080:8080
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080",
      ]
    network_mode: bridge
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy:/etc/nginx/vhost.d
      - proxy:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    network_mode: bridge
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - proxy:/etc/nginx/vhost.d
      - proxy:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    network_mode: bridge
    restart: always

volumes:
  proxy:
