name: URL Health Check

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: Jtalk/url-health-check-action@v1
        with:
          url: https://swift-ast-explorer.com|https://www.swift-ast-explorer.com|https://swift-ast-explorer.kishikawakatsumi.com
          follow-redirect: yes
          max-attempts: 3
          retry-delay: 5s
